version: '3'

services:
  web:
    image: node:20
    container_name: nextjs_app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    command: npm run dev
